Add useful stacktraces

diff --git a/src/bash-specs b/src/bash-specs
--- a/src/bash-specs
+++ b/src/bash-specs
@@ -25,6 +25,7 @@ readonly tmp_dir=${TMPDIR}/${RANDOM}.${RANDOM}.$$
 readonly elapsed_time=${tmp_dir}/elapsed_time
 readonly total_elapsed_time=${tmp_dir}/total_elapsed_time
 readonly stderr=${tmp_dir}/stderr
+readonly errors=${tmp_dir}/errors
 
 readonly number_of_specs=${tmp_dir}/number_of_specs
 readonly number_of_failed_specs=${tmp_dir}/number_of_failed_specs
@@ -193,7 +194,7 @@ it() {
   fi
 
   total_elapsed=0
-  > "$stderr"
+  > "$errors"
 
   __exec before_each && 
   __exec "$2"
@@ -217,18 +218,26 @@ it() {
 
   __print_spec_result "$fail" "$1" "$total_elapsed"
 
-  if [[ -s "$stderr" ]]; then
-    printf '    %s\n' "$(< "$stderr")"
+  if [[ -s "$errors" ]]; then
+    printf '    %s:\n' "${BASH_SOURCE[1]}"
+    printf '%s\n' "$(< "$errors")"
   fi
 
   [[ $fail_fast == true ]] && exit 1
 }
 
 __exec() {
-#  trap "__trace $1" ERR
-  { time "$1" > /dev/null 2>> "$stderr"; } 2> "$elapsed_time"
+  set -e
+  { time "$1" > /dev/null 2> "$stderr"; } 2> "$elapsed_time"
   local result=$?
-#  trap - ERR
+  set +e
+
+  if ((result > 0)); then
+    local err="$(< "$stderr")"
+    [[ -z "$err" ]] && err='The function exited with a non-zero status'
+    printf '      %s:\n' "$1" >> "$errors"
+    printf '        %s\n' "$err" >> "$errors" 
+  fi
 
   local elapsed=$(< "$elapsed_time")
   ((total_elapsed += 10#${elapsed/./}))
