Add color reset

diff --git a/src/bash-specs b/src/bash-specs
--- a/src/bash-specs
+++ b/src/bash-specs
@@ -21,16 +21,15 @@ LC_NUMERIC=C
 TIMEFORMAT=%R
 : ${TMPDIR:=/tmp}
 
-
 readonly version_number=1.0.0
 
 readonly red=$(tput setaf 1)
 readonly green=$(tput setaf 2)
 readonly cyan=$(tput setaf 6)
-readonly default_color=$(tput setaf 9)
+readonly reset=$(tput sgr0)
 
 readonly tmp_dir=${TMPDIR}/${RANDOM}.${RANDOM}.$$
-readonly elapsed_time_file=${tmp_dir}/elapsed_time.out
+readonly elapsed_time_file=${tmp_dir}/elapsed_time
 
 number_of_specs=0
 number_of_specs_failed=0
@@ -45,7 +44,7 @@ main() {
   printf 'bash-specs %s\n' "$version_number"
 
   mkdir -m 700 "$tmp_dir"
-  trap '__cleanup_exit' EXIT
+  trap '__cleanup' EXIT
 
   for suite; do
     . "$suite"
@@ -55,7 +54,7 @@ main() {
 }
 
 describe() {
-  printf '\n%s%s\n' "$default_color" "$1"
+  printf '\n%s\n' "$1"
 }
 
 before_each() {
@@ -63,29 +62,11 @@ before_each() {
 }
 
 expect() {
-  $2 $1 ${@:3}
+  "$2" "$1" "${@:3}"
 }
 
 to_equal() {
-  if is_array $1; then
-    if ((${#1[@]} != ${#2[@]})); then
-      __build_error_message "$1" "$FUNCNAME" "$2"
-
-      return 1
-    fi
-
-    for ((i = 0; i < ${#1[@]}; i++)); do
-      if  [[ ${1[i]} != ${2[i]} ]]; then
-        __build_error_message "$1" "$FUNCNAME" "$2"
-
-        return 1
-      fi
-    done
-
-    return 0
-  fi
-
-  (($1 == $2)) && return 0
+  [[ $1 == $2 ]] && return 0
 
   __build_error_message "$1" "$FUNCNAME" "$2"
 
@@ -109,16 +90,6 @@ to_be_greater_than() {
 }
 
 to_contain() {
-  if is_array $1; then
-    for e in $1; do
-      [[ $e == $2 ]] && return 0
-    done
-
-    __build_error_message "$1" "$FUNCNAME" "$2"
-
-    return 1
-  fi 
-
   [[ $1 == *$2* ]] && return 0
 
   __build_error_message "$1" "$FUNCNAME" "$2"
@@ -134,10 +105,6 @@ to_match() {
 
 __build_error_message() {
   error_message="Expected '$1' ${2//_/ } '$3'."
-}
-
-__is_array() {
-  [[ $(declare -p $1) == "declare -a"* ]]
 }
 
 it() {
@@ -179,7 +146,7 @@ __accumulate_total_elapsed_time() {
 }
 
 __print_spec_result() {
-  printf '%s  %s%s (%.3f s)\n' "$1" "$2" "$cyan" "$3"
+  printf '%s  %s%s (%.3f s)%s\n' "$1" "$2" "$cyan" "$3" "$reset"
 }
 
 xit() {
@@ -190,8 +157,8 @@ after_each() {
   :
 }
 
-__cleanup_exit() {
-  tput sgr0
+__cleanup() {
+  rm -rf "$tmp_dir"
 }
 
 __print_summary() {
@@ -202,7 +169,7 @@ __print_summary() {
   local secs=$((total_elapsed_time / 1000))
   local millisecs=$((total_elapsed_time % 1000))
 
-  printf '\n%s%s %s, %s failed%s (%d.%03d s)%s\n' "$color" "$number_of_specs" "$units" "$number_of_specs_failed" "$cyan" "$secs" "$millisecs" "$default_color"
+  printf '\n%s%s %s, %s failed%s (%d.%03d s)%s\n' "$color" "$number_of_specs" "$units" "$number_of_specs_failed" "$cyan" "$secs" "$millisecs" "$reset"
 }
 
 main "$@"
